[
    RuntimeEnabled=WebAnimationsAPI,
] interface TestJS {
    // Playback state
    readonly attribute double? localTime;
    readonly attribute unsigned long? currentIteration;

    // Calculated timing
    readonly attribute double startTime;
    readonly attribute double duration;
    readonly attribute double activeDuration;
    readonly attribute double endTime;

    readonly attribute Timing specified;
    readonly attribute Player? player;
};
